server:
  port: 9004
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: order-service
logging:
  file: 
    name: D:/work/www-architecture/microservice.log
  

